version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-petshop
    restart: always
    environment:
      POSTGRES_DB: petshop
      POSTGRES_USER: petshop
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"